### ISSUE TITLE
Build the Login and Register Page

### ISSUE THREAD

**Issue by Utkub24** [witch-puzzles/frontend-puzzles#11]
## Description
We should create the login page (route `/login`) with the required content.

Use [Svelte Material UI](https://sveltematerialui.com/) components, add new ones as necessary.

> [!WARNING]
> _**Do not make**_ any calls to the backend and/or foreign API.

## Layout Reference
![Login Page](https://github.com/user-attachments/assets/95d33322-9f22-433d-a7a4-7bca52eec819)

## Acceptance Criteria
- Adheres to the above layout as closely as possible.
- Uses Svelte Material UI as much as possible.

**Comment by lucashlz** [comment]
done, also did the register page with only email and password field

**Comment by Utkub24** [comment]
Thanks  @lucashlz, closed by 705874c4c854f27b0d43a8d09e42b2b3dd4b5c2c
