### ISSUE TITLE
Build the Top Bar

### ISSUE THREAD

**Issue by Utkub24** [witch-puzzles/frontend-puzzles#16]
## Description
We should create the top bar that appears in multiple pages with the required content.

Use [Svelte Material UI](https://sveltematerialui.com/) components, add new ones as necessary.

> [!WARNING]
> _**Do not make**_ any calls to the backend and/or foreign API.

## Layout Reference
![Top Bar](https://github.com/user-attachments/assets/42c60899-c219-4ad8-96cf-265f2079f810)

## Acceptance Criteria
- Appears on _**only**_ the pages it needs to
    - Uses Svelte's `+layout` feature.
- Adheres to the above layout as closely as possible.
- Uses Svelte Material UI as much as possible.

**Comment by lucashlz** [comment]
done, waiting for your review

**Comment by Utkub24** [comment]
Thank you @lucashlz, closed by 23bc089e6ec000c2cc8d27e19cb71f2a2c39ba55
