### ISSUE TITLE
Choose a Component Library for Svelte

### ISSUE THREAD

**Issue by Utkub24** [witch-puzzles/frontend-puzzles#4]
**Describe the feature**

We would like to use a component library so that we spend less time on styling and more time developing features.

**Additional context**

**Comment by atatrkz** [comment]
I've done the research and stumbled upon two main easy to use component libraries for svelte: SvelteStrap (Bootstrap for Svelte) and Svelte Material UI (Material Design for Svelte). SvelteStrap would be easier and faster to implement while Svelte Material UI would result in a more modern UI. Will decide with Lucas to finalize the decision.

**Comment by Utkub24** [comment]
IMHO, I like the Bootstrap look better than the Material one. Wdyt @lucashlz ?

**Comment by Utkub24** [comment]
Material UI looks good :+1:
 Wdyt @lucashlz ?
